from functools import lru_cache
from pathlib import Path

from dotenv import load_dotenv
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

ENV_PATH = Path(__file__).resolve().parents[1] / ".env"
load_dotenv(ENV_PATH, override=True, encoding="utf-8-sig")


class Settings(BaseSettings):
    telegram_bot_token: str = Field(default="", alias="TELEGRAM_BOT_TOKEN")
    telegram_use_webhook: bool = Field(default=False, alias="TELEGRAM_USE_WEBHOOK")
    telegram_webhook_url: str = Field(default="", alias="TELEGRAM_WEBHOOK_URL")
    telegram_webhook_secret: str = Field(default="", alias="TELEGRAM_WEBHOOK_SECRET")
    vercel: bool = Field(default=False, alias="VERCEL")
    cron_secret: str = Field(default="", alias="CRON_SECRET")
    gemini_api_key: str = Field(default="", alias="GEMINI_API_KEY")
    gemini_model: str = Field(default="gemini-2.5-flash-lite", alias="GEMINI_MODEL")
    openai_api_key: str = Field(default="", alias="OPENAI_API_KEY")
    openai_model: str = Field(default="gpt-4.1-mini", alias="OPENAI_MODEL")
    openai_base_url: str = Field(default="https://api.openai.com/v1", alias="OPENAI_BASE_URL")
    openrouter_api_key: str = Field(default="", alias="OPENROUTER_API_KEY")
    openrouter_model: str = Field(default="nvidia/nemotron-3-ultra-550b-a55b:free", alias="OPENROUTER_MODEL")
    openrouter_base_url: str = Field(default="https://openrouter.ai/api/v1", alias="OPENROUTER_BASE_URL")
    ai_provider_order: str = Field(default="openrouter,gemini,openai", alias="AI_PROVIDER_ORDER")
    import_generate_limit: int = Field(default=2, alias="IMPORT_GENERATE_LIMIT")
    startup_import_csv_path: str = Field(default="", alias="STARTUP_IMPORT_CSV_PATH")
    startup_generate_limit: int = Field(default=2, alias="STARTUP_GENERATE_LIMIT")
    base_url: str = Field(default="http://localhost:8000", alias="BASE_URL")
    database_url: str = Field(default="sqlite:///./affiliate_agent.db", alias="DATABASE_URL")
    tracking_port: int = Field(default=8000, alias="TRACKING_PORT")
    threads_access_token: str = Field(default="", alias="THREADS_ACCESS_TOKEN")
    threads_user_id: str = Field(default="", alias="THREADS_USER_ID")
    threads_api_base_url: str = Field(default="https://graph.threads.net/v1.0", alias="THREADS_API_BASE_URL")
    include_tracking_link_in_threads: bool = Field(default=False, alias="INCLUDE_TRACKING_LINK_IN_THREADS")
    post_tracking_link_as_reply: bool = Field(default=True, alias="POST_TRACKING_LINK_AS_REPLY")
    comment_link_target: str = Field(default="affiliate", alias="COMMENT_LINK_TARGET")
    telegram_community_group_id: str = Field(default="", alias="TELEGRAM_COMMUNITY_GROUP_ID")
    telegram_group_invite_url: str = Field(default="", alias="TELEGRAM_GROUP_INVITE_URL")
    telegram_group_display_name: str = Field(default="Nhom link uu dai", alias="TELEGRAM_GROUP_DISPLAY_NAME")
    telegram_daily_link_disclosure: str = Field(
        default="Cac link tren la link tiep thi lien ket.",
        alias="TELEGRAM_DAILY_LINK_DISCLOSURE",
    )
    telegram_daily_disable_link_preview: bool = Field(default=True, alias="TELEGRAM_DAILY_DISABLE_LINK_PREVIEW")
    daily_links_per_message: int = Field(default=5, alias="DAILY_LINKS_PER_MESSAGE")
    daily_max_products_per_category: int = Field(default=20, alias="DAILY_MAX_PRODUCTS_PER_CATEGORY")
    daily_max_products_per_send: int = Field(default=10, alias="DAILY_MAX_PRODUCTS_PER_SEND")
    daily_enable_pagination: bool = Field(default=True, alias="DAILY_ENABLE_PAGINATION")
    daily_default_link_type: str = Field(default="shopee_commission", alias="DAILY_DEFAULT_LINK_TYPE")
    daily_link_default_target: str = Field(default="group", alias="DAILY_LINK_DEFAULT_TARGET")
    daily_group_send_cooldown_seconds: int = Field(default=30, alias="DAILY_GROUP_SEND_COOLDOWN_SECONDS")
    daily_link_retention_days: int = Field(default=4, alias="DAILY_LINK_RETENTION_DAYS")
    daily_link_cleanup_hour: int = Field(default=3, alias="DAILY_LINK_CLEANUP_HOUR")
    daily_link_timezone: str = Field(default="Asia/Bangkok", alias="DAILY_LINK_TIMEZONE")
    daily_link_delete_orphan_products: bool = Field(default=True, alias="DAILY_LINK_DELETE_ORPHAN_PRODUCTS")
    threads_include_telegram_cta: bool = Field(default=True, alias="THREADS_INCLUDE_TELEGRAM_CTA")
    threads_telegram_cta_mode: str = Field(default="reply", alias="THREADS_TELEGRAM_CTA_MODE")
    threads_telegram_group_url: str = Field(default="", alias="THREADS_TELEGRAM_GROUP_URL")
    threads_telegram_group_name: str = Field(default="nhom link uu dai", alias="THREADS_TELEGRAM_GROUP_NAME")
    import_external_threads_posts: bool = Field(default=False, alias="IMPORT_EXTERNAL_THREADS_POSTS")
    threads_analytics_sync_enabled: bool = Field(default=True, alias="THREADS_ANALYTICS_SYNC_ENABLED")
    threads_analytics_sync_interval_minutes: int = Field(default=60, alias="THREADS_ANALYTICS_SYNC_INTERVAL_MINUTES")
    threads_replies_sync_enabled: bool = Field(default=True, alias="THREADS_REPLIES_SYNC_ENABLED")
    threads_keyword_search_enabled: bool = Field(default=False, alias="THREADS_KEYWORD_SEARCH_ENABLED")
    threads_insights_lookback_days: int = Field(default=30, alias="THREADS_INSIGHTS_LOOKBACK_DAYS")
    threads_learning_min_posts: int = Field(default=10, alias="THREADS_LEARNING_MIN_POSTS")
    threads_auto_learn_interval_hours: int = Field(default=6, alias="THREADS_AUTO_LEARN_INTERVAL_HOURS")
    threads_reply_retention_days: int = Field(default=90, alias="THREADS_REPLY_RETENTION_DAYS")
    threads_keyword_sample_retention_days: int = Field(default=7, alias="THREADS_KEYWORD_SAMPLE_RETENTION_DAYS")
    threads_demand_scanner_enabled: bool = Field(default=False, alias="THREADS_DEMAND_SCANNER_ENABLED")
    threads_demand_min_score: int = Field(default=70, alias="THREADS_DEMAND_MIN_SCORE")
    threads_demand_max_results_per_scan: int = Field(default=10, alias="THREADS_DEMAND_MAX_RESULTS_PER_SCAN")
    threads_demand_max_approve_batch: int = Field(default=5, alias="THREADS_DEMAND_MAX_APPROVE_BATCH")
    threads_demand_max_reply_batch: int = Field(default=3, alias="THREADS_DEMAND_MAX_REPLY_BATCH")
    threads_demand_max_replies_per_account_per_day: int = Field(default=3, alias="THREADS_DEMAND_MAX_REPLIES_PER_ACCOUNT_PER_DAY")
    threads_demand_reply_cooldown_minutes: int = Field(default=30, alias="THREADS_DEMAND_REPLY_COOLDOWN_MINUTES")
    threads_demand_opportunity_ttl_hours: int = Field(default=36, alias="THREADS_DEMAND_OPPORTUNITY_TTL_HOURS")
    threads_demand_max_links_per_comment: int = Field(default=4, alias="THREADS_DEMAND_MAX_LINKS_PER_COMMENT")
    threads_demand_manual_approval_required: bool = Field(default=True, alias="THREADS_DEMAND_MANUAL_APPROVAL_REQUIRED")
    enable_daily_link_catalog: bool = Field(default=True, alias="ENABLE_DAILY_LINK_CATALOG")
    enable_threads_engagement_posts: bool = Field(default=True, alias="ENABLE_THREADS_ENGAGEMENT_POSTS")
    enable_telegram_group: bool = Field(default=True, alias="ENABLE_TELEGRAM_GROUP")
    enable_telegram_channel: bool = Field(default=False, alias="ENABLE_TELEGRAM_CHANNEL")
    enable_daily_link_auto_cleanup: bool = Field(default=True, alias="ENABLE_DAILY_LINK_AUTO_CLEANUP")
    enable_demand_scanner: bool = Field(default=False, alias="ENABLE_DEMAND_SCANNER")
    enable_manual_demand_intake: bool = Field(default=False, alias="ENABLE_MANUAL_DEMAND_INTAKE")
    enable_purchase_intent: bool = Field(default=False, alias="ENABLE_PURCHASE_INTENT")
    enable_product_matcher: bool = Field(default=False, alias="ENABLE_PRODUCT_MATCHER")
    enable_comment_generator: bool = Field(default=False, alias="ENABLE_COMMENT_GENERATOR")
    enable_opportunity_queue: bool = Field(default=False, alias="ENABLE_OPPORTUNITY_QUEUE")
    enable_approval_queue: bool = Field(default=False, alias="ENABLE_APPROVAL_QUEUE")
    enable_threads_publisher: bool = Field(default=True, alias="ENABLE_THREADS_PUBLISHER")
    enable_manual_copy_mode: bool = Field(default=True, alias="ENABLE_MANUAL_COPY_MODE")
    enable_basic_analytics: bool = Field(default=True, alias="ENABLE_BASIC_ANALYTICS")
    enable_content_engine: bool = Field(default=True, alias="ENABLE_CONTENT_ENGINE")
    enable_engagement_posts: bool = Field(default=True, alias="ENABLE_ENGAGEMENT_POSTS")
    enable_learning_engine: bool = Field(default=False, alias="ENABLE_LEARNING_ENGINE")
    enable_topic_memory: bool = Field(default=False, alias="ENABLE_TOPIC_MEMORY")
    enable_persona_optimizer: bool = Field(default=False, alias="ENABLE_PERSONA_OPTIMIZER")
    enable_hook_optimizer: bool = Field(default=False, alias="ENABLE_HOOK_OPTIMIZER")
    enable_cta_optimizer: bool = Field(default=False, alias="ENABLE_CTA_OPTIMIZER")
    enable_diversity_engine: bool = Field(default=False, alias="ENABLE_DIVERSITY_ENGINE")
    enable_marketplace_intelligence: bool = Field(default=False, alias="ENABLE_MARKETPLACE_INTELLIGENCE")
    enable_trend_fusion: bool = Field(default=False, alias="ENABLE_TREND_FUSION")
    enable_google_trends: bool = Field(default=False, alias="ENABLE_GOOGLE_TRENDS")
    enable_threads_trend_provider: bool = Field(default=False, alias="ENABLE_THREADS_TREND_PROVIDER")
    enable_instagram_provider: bool = Field(default=False, alias="ENABLE_INSTAGRAM_PROVIDER")
    enable_facebook_provider: bool = Field(default=False, alias="ENABLE_FACEBOOK_PROVIDER")
    enable_x_provider: bool = Field(default=False, alias="ENABLE_X_PROVIDER")
    enable_reddit_provider: bool = Field(default=False, alias="ENABLE_REDDIT_PROVIDER")
    enable_cross_platform_publisher: bool = Field(default=False, alias="ENABLE_CROSS_PLATFORM_PUBLISHER")
    enable_threads_background_sync: bool = Field(default=False, alias="ENABLE_THREADS_BACKGROUND_SYNC")
    enable_threads_auto_scanner: bool = Field(default=False, alias="ENABLE_THREADS_AUTO_SCANNER")
    demand_min_intent_score: int = Field(default=70, alias="DEMAND_MIN_INTENT_SCORE")
    demand_max_results_per_review: int = Field(default=5, alias="DEMAND_MAX_RESULTS_PER_REVIEW")
    demand_max_approve_batch: int = Field(default=5, alias="DEMAND_MAX_APPROVE_BATCH")
    demand_max_reply_batch: int = Field(default=3, alias="DEMAND_MAX_REPLY_BATCH")
    demand_max_replies_per_account_per_day: int = Field(default=3, alias="DEMAND_MAX_REPLIES_PER_ACCOUNT_PER_DAY")
    demand_reply_cooldown_minutes: int = Field(default=30, alias="DEMAND_REPLY_COOLDOWN_MINUTES")
    demand_opportunity_ttl_hours: int = Field(default=36, alias="DEMAND_OPPORTUNITY_TTL_HOURS")
    demand_max_links_per_comment: int = Field(default=4, alias="DEMAND_MAX_LINKS_PER_COMMENT")
    demand_manual_approval_required: bool = Field(default=True, alias="DEMAND_MANUAL_APPROVAL_REQUIRED")
    demand_intake_api_enabled: bool = Field(default=False, alias="DEMAND_INTAKE_API_ENABLED")
    demand_intake_api_key: str = Field(default="", alias="DEMAND_INTAKE_API_KEY")

    model_config = SettingsConfigDict(env_file=str(ENV_PATH), env_file_encoding="utf-8-sig", extra="ignore")


@lru_cache
def get_settings() -> Settings:
    return Settings()
